name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure toolchains
      run: |
        wget https://github.com/YuzukiHD/FreeRTOS-HIFI4-DSP/releases/download/Toolchains/xtensa-hifi4-dsp.tar.gz
        mkdir -p ${{github.workspace}}/toolchains
        mv xtensa-hifi4-dsp.tar.gz ${{github.workspace}}/toolchains/
        cd ${{github.workspace}}/toolchains
        tar xvf xtensa-hifi4-dsp.tar.gz
      
    - name: make
      run: CROSS_COMPILE=${{github.workspace}}/toolchains/bin/xtensa-hifi4-elf- make 
      
